"""empty message

Revision ID: 1ea553645967
Revises: 14b3a3749594
Create Date: 2022-04-11 17:25:51.928424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea553645967'
down_revision = '14b3a3749594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['Comment_id'], ['id'])
    op.add_column('user', sa.Column('img', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
