"""empty message

Revision ID: 2a83f7b80b4c
Revises: 7760f8c09023
Create Date: 2022-03-28 13:43:55.186175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a83f7b80b4c'
down_revision = '7760f8c09023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cature', 'cat')
    op.create_foreign_key(None, 'comment', 'user', ['Comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.add_column('cature', sa.Column('cat', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
