"""empty message

Revision ID: 7760f8c09023
Revises: 8a6dc322434e
Create Date: 2022-03-24 15:19:49.181162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7760f8c09023'
down_revision = '8a6dc322434e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cature', sa.Column('cat', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'comment', 'user', ['Comment_id'], ['id'])
    op.add_column('source', sa.Column('source_title', sa.String(length=100), nullable=True))
    op.add_column('source', sa.Column('source_img', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'source_img')
    op.drop_column('source', 'source_title')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('cature', 'cat')
    # ### end Alembic commands ###
