"""empty message

Revision ID: 8a6dc322434e
Revises: 67c5f631bc90
Create Date: 2022-03-22 18:45:15.862233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6dc322434e'
down_revision = '67c5f631bc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_contact', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['Comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'comment_contact')
    # ### end Alembic commands ###
